### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by tomasfejfar** [pear/VersionControl_Git#15]
When installed via composer it's missing a dependency (https://github.com/pear/VersionControl_Git/blob/master/VersionControl/Git.php#L27). The "system" file is part of https://packagist.org/packages/pear/pear-core-minimal

**Comment by gboddin** [comment]
Yes I hit that issue as well
Requiring     "pear/pear": "dev-master" fix the issue

**Comment by gboddin** [comment]
To be clear, the issue is triggered when you work on a system without a /usr/share/php version of pear (which is usually installed by default on most distribution but is not required per say).

Regards,

**Comment by pfrenssen** [comment]
Since we only need the {{System.php}} file we could also use the alternative lightweight package [pear/pear-core-minimal](https://github.com/pear/pear-core-minimal) which is intended for use cases like this.

Either solution is good to me.

For people wondering about depending on the "dev-master" branch, this is fine since this branch is only updated when a new upstream release is made.

**Comment by gboddin** [comment]
It seems better indeed.

I updated the PR #16

**Comment by pfrenssen** [comment]
This looks great to me, thanks!
